# Local costmap (used for real-time obstacle avoidance)

local_costmap:
  global_frame: odom            # Reference frame for local movement
  robot_base_frame: base_link   # Robot's base frame
  update_frequency: 5.0         # Hz at which the map is updated
  publish_frequency: 2.0        # Hz at which the map is published
  rolling_window: true          # Enables a moving window around the robot
  width: 6.0                    # Width of the local costmap in meters
  height: 4.0                   # Height of the local costmap in meters
  resolution: 0.05              # Meters per cell
  static_map: false             # Do not use a static map (local costmap is dynamic)
  transform_tolerance: 1.0
